
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Devang Chhajed
 */
public class fpassword extends javax.swing.JFrame {

    /**
     * Creates new form fpassword
     */
    public fpassword() {
        initComponents();
         this.setIconImage(new ImageIcon(getClass().getResource("ico.png")).getImage());
        Toolkit toolkit = Toolkit.getDefaultToolkit();

Image img = toolkit.getImage("cur1.png");

Point point = new Point(0,0);
        Cursor cursor=toolkit.createCustomCursor(img, point, "Cursor"); 

   setCursor(cursor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fuser = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jp2 = new javax.swing.JPasswordField();
        jp1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fsecque = new javax.swing.JTextField();
        fsecans = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm Passwrd :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 100, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("New Password :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 100, 20));
        getContentPane().add(fuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 210, -1));

        jButton2.setText("Confirm User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 140, -1));

        jp2.setEditable(false);
        jp2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jp2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(1)));
        jp2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jp2KeyPressed(evt);
            }
        });
        getContentPane().add(jp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 210, 20));

        jp1.setEditable(false);
        jp1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jp1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(1)));
        jp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jp1KeyPressed(evt);
            }
        });
        getContentPane().add(jp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 360, 20));

        jButton3.setText("Change Password");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 140, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Security Answer : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 100, 20));

        fsecque.setEditable(false);
        getContentPane().add(fsecque, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 360, -1));

        fsecans.setEditable(false);
        getContentPane().add(fsecans, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 210, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username : ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 100, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Security Question : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 100, 20));

        jButton1.setText("Check Answer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 140, -1));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Backgrounds/slide4.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, 0, -1, 360));

        setSize(new java.awt.Dimension(610, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String user=fuser.getText(); 
String ans=fsecans.getText(); 

try{
Class.forName("java.sql.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
Statement s=conn.createStatement();
String q= "select * from admina where UserID=\""+user+"\"";
ResultSet rs=s.executeQuery(q);
rs.first();
String fans=rs.getString("SecAns");
if(ans.compareToIgnoreCase(fans)==0)
{
    JOptionPane.showMessageDialog(null,"Now you can change the Password");
    jp1.setEditable(true);
    jp2.setEditable(true);

    
}

}catch(Exception e){
JOptionPane.showMessageDialog(null,e);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String user=fuser.getText();        
try{
Class.forName("java.sql.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
Statement s=conn.createStatement();
String q= "select * from devangproject.admina where UserID=\""+user+"\"";
ResultSet rs=s.executeQuery(q);
rs.first();
fsecque.setText(rs.getString("SecQue"));
fsecans.setEditable(true);
   
}catch(Exception e){
JOptionPane.showMessageDialog(null,e);}
        
        
        
        
        
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jp2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jp2KeyPressed
               // TODO add your handling code here:
    }//GEN-LAST:event_jp2KeyPressed

    private void jp1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jp1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jp1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String user=fuser.getText(); 
String p1= new String (jp1.getPassword());
String p2= new String (jp2.getPassword());

if(p1.compareTo(p2)==0)
{



try{
Class.forName("java.sql.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
Statement s=conn.createStatement();
String q= "update admina set UserPass=\""+p1+"\" where UserID=\""+user+"\"";
int x=s.executeUpdate(q);

            if (x>0)
                JOptionPane.showMessageDialog(null, "Password Changed Successfully..");
            else
                JOptionPane.showMessageDialog(null, "Password not Changed");


}catch(Exception e){
JOptionPane.showMessageDialog(null,e);}
        
}else{

JOptionPane.showMessageDialog(null, "Password do not Match");
}       
        
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fpassword().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fsecans;
    private javax.swing.JTextField fsecque;
    private javax.swing.JTextField fuser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jp1;
    private javax.swing.JPasswordField jp2;
    // End of variables declaration//GEN-END:variables
}
