
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vipin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
         this.setIconImage(new ImageIcon(getClass().getResource("ico.png")).getImage());
         Toolkit toolkit = Toolkit.getDefaultToolkit();

Image img = toolkit.getImage("cur1.png");

Point point = new Point(0,0);
        Cursor cursor=toolkit.createCustomCursor(img, point, "Cursor"); 

   setCursor(cursor);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Admin");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 150, 40));

        jPasswordField1.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setText("Password");
        jPasswordField1.setBorder(null);
        jPasswordField1.setOpaque(false);
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 320, 60));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("UserName");
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 320, 50));

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 150, 40));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 140, 20));

        jLabel1.setToolTipText("Back");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 60, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 599, 600));

        setSize(new java.awt.Dimension(597, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
    
     main1 ob = new main1();
    
   String user=jTextField1.getText();
   String pwd= new String (jPasswordField1.getPassword());

   if(user.isEmpty() || user.compareTo("UserName")==0)
 {   try {
 // Open an audio input stream.
 URL url = this.getClass().getClassLoader().getResource("Sound/username.wav");
 AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
 // Get a sound clip resource.
 Clip clip = AudioSystem.getClip();
 // Open audio clip and load samples from the audio input stream.
 clip.open(audioIn);
 clip.start();
 } catch (Exception e1) {
 e1.printStackTrace();
 } 
 
 }
   else
   if(pwd.isEmpty() || pwd.compareTo("Password")==0)
 {  try {
 // Open an audio input stream.
 URL url = this.getClass().getClassLoader().getResource("Sound/password.wav");
 AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
 // Get a sound clip resource.
 Clip clip = AudioSystem.getClip();
 // Open audio clip and load samples from the audio input stream.
 clip.open(audioIn);
 clip.start();
 } catch (Exception e1) {
 e1.printStackTrace();
 } 
 }
       else{



String pass = null, name=null;
try{
        
Class.forName("java.sql.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
Statement s=conn.createStatement();
String q= "select * from admina where UserID=\""+user+"\"";
ResultSet rs=s.executeQuery(q);
rs.first();
pass=rs.getString("UserPass");
name=rs.getString("Name");
ob.vusnam=name;
ob.vusid=user;
}catch(Exception e){
      JOptionPane.showMessageDialog(this, "Incorrect Username or Password!");
 try {
 // Open an audio input stream.
 URL url = this.getClass().getClassLoader().getResource("Sound/Denied.wav");
 AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
 // Get a sound clip resource.
 Clip clip = AudioSystem.getClip();
 // Open audio clip and load samples from the audio input stream.
 clip.open(audioIn);
 clip.start();
 } catch (Exception e1) {
 e1.printStackTrace();
 } 


}



if (pwd.compareTo(pass)==0)
{    ob.vusid=user;

   try {
 // Open an audio input stream.
 URL url = this.getClass().getClassLoader().getResource("Sound/access.wav");
 AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
 // Get a sound clip resource.
 Clip clip = AudioSystem.getClip();
 // Open audio clip and load samples from the audio input stream.
 clip.open(audioIn);
 clip.start();
 } catch (Exception e1) {
 e1.printStackTrace();
 } 

       
       
       
       
       
         Calendar cal=new GregorianCalendar();
         int m=cal.get(Calendar.MONTH);
         int y=cal.get(Calendar.YEAR);
         int d=cal.get(Calendar.DAY_OF_MONTH);
         String month;

        String date=y+"-"+(m+1)+"-"+d;
   
   
         int sec=cal.get(Calendar.SECOND);
         int min=cal.get(Calendar.MINUTE);
         int hr=cal.get(Calendar.HOUR);
         int mm=cal.get(Calendar.AM_PM);
         String mmm;
         if (mm==0)
             mmm="AM";
         else
             mmm="PM";
         String time=+hr+"-"+min+"-"+sec+" "+mmm;  
       
       
       
       
       
       try{
        
Class.forName("java.sql.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
Statement s=conn.createStatement();
String q= "insert into history values(\""+date+"\" , \""+ob.vusid+"\" , \""+ob.vusnam+"\" , \""+time+"\" , \" Loggged In \" )";
int rs=s.executeUpdate(q);
       
       }catch(Exception e){}
       
       
       
       
Adminpanel s=new Adminpanel();
 s.setVisible(true);
 this.dispose();


this.dispose();

}else {ob.vusid=user;
   try {
 // Open an audio input stream.
 URL url = this.getClass().getClassLoader().getResource("Sound/Denied.wav");
 AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
 // Get a sound clip resource.
 Clip clip = AudioSystem.getClip();
 // Open audio clip and load samples from the audio input stream.
 clip.open(audioIn);
 clip.start();
 } catch (Exception e1) {
 e1.printStackTrace();
 } 

JOptionPane.showMessageDialog(this, "Incorrect Username or Password!");
}}
    
    
    
    
    
    
    
}
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
fpassword s=new fpassword();
s.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked

        String a=jTextField1.getText();
        if(a.compareTo("UserName")==0)
        {jTextField1.setText("");
        }
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
String b=new String (jPasswordField1.getPassword());
        if(b.compareToIgnoreCase("Password")==0)
        {jPasswordField1.setText("");
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
  main1 ob = new main1();
    
   String user=jTextField1.getText();
   String pwd= new String (jPasswordField1.getPassword());

   if(user.isEmpty() || user.compareTo("UserName")==0)
 {   try {
 // Open an audio input stream.
 URL url = this.getClass().getClassLoader().getResource("Sound/username.wav");
 AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
 // Get a sound clip resource.
 Clip clip = AudioSystem.getClip();
 // Open audio clip and load samples from the audio input stream.
 clip.open(audioIn);
 clip.start();
 } catch (Exception e1) {
 e1.printStackTrace();
 } 
 
 }
   else
   if(pwd.isEmpty() || pwd.compareTo("Password")==0)
 {  try {
 // Open an audio input stream.
 URL url = this.getClass().getClassLoader().getResource("Sound/password.wav");
 AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
 // Get a sound clip resource.
 Clip clip = AudioSystem.getClip();
 // Open audio clip and load samples from the audio input stream.
 clip.open(audioIn);
 clip.start();
 } catch (Exception e1) {
 e1.printStackTrace();
 } 
 }
       else{



String pass = null, name=null;
try{
        
Class.forName("java.sql.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
Statement s=conn.createStatement();
String q= "select * from admina where UserID=\""+user+"\"";
ResultSet rs=s.executeQuery(q);
rs.first();
pass=rs.getString("UserPass");
name=rs.getString("Name");
ob.vusnam=name;
ob.vusid=user;
}catch(Exception e){
      JOptionPane.showMessageDialog(this, "Incorrect Username or Password!");
 try {
 // Open an audio input stream.
 URL url = this.getClass().getClassLoader().getResource("Sound/Denied.wav");
 AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
 // Get a sound clip resource.
 Clip clip = AudioSystem.getClip();
 // Open audio clip and load samples from the audio input stream.
 clip.open(audioIn);
 clip.start();
 } catch (Exception e1) {
 e1.printStackTrace();
 } 


}



if (pwd.compareTo(pass)==0)
{    ob.vusid=user;

   try {
 // Open an audio input stream.
 URL url = this.getClass().getClassLoader().getResource("Sound/access.wav");
 AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
 // Get a sound clip resource.
 Clip clip = AudioSystem.getClip();
 // Open audio clip and load samples from the audio input stream.
 clip.open(audioIn);
 clip.start();
 } catch (Exception e1) {
 e1.printStackTrace();
 } 

       
       
       
       
       
         Calendar cal=new GregorianCalendar();
         int m=cal.get(Calendar.MONTH);
         int y=cal.get(Calendar.YEAR);
         int d=cal.get(Calendar.DAY_OF_MONTH);
         String month;

        String date=y+"-"+(m+1)+"-"+d;
   
   
         int sec=cal.get(Calendar.SECOND);
         int min=cal.get(Calendar.MINUTE);
         int hr=cal.get(Calendar.HOUR);
         int mm=cal.get(Calendar.AM_PM);
         String mmm;
         if (mm==0)
             mmm="AM";
         else
             mmm="PM";
         String time=+hr+"-"+min+"-"+sec+" "+mmm;  
       
       
       
       
       
       try{
        
Class.forName("java.sql.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
Statement s=conn.createStatement();
String q= "insert into history values(\""+date+"\" , \""+ob.vusid+"\" , \""+ob.vusnam+"\" , \""+time+"\" , \" Loggged In \" )";
int rs=s.executeUpdate(q);
       
       }catch(Exception e){}
       
       
       
       
Adminpanel s=new Adminpanel();
 s.setVisible(true);
 this.dispose();


this.dispose();

}else {ob.vusid=user;
   try {
 // Open an audio input stream.
 URL url = this.getClass().getClassLoader().getResource("Sound/Denied.wav");
 AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
 // Get a sound clip resource.
 Clip clip = AudioSystem.getClip();
 // Open audio clip and load samples from the audio input stream.
 clip.open(audioIn);
 clip.start();
 } catch (Exception e1) {
 e1.printStackTrace();
 } 

JOptionPane.showMessageDialog(this, "Incorrect Username or Password!");
}}
   
           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
nuser s=new nuser();
s.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
