
import java.awt.Image;
import java.awt.Rectangle;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Devang Chhajed
 */
public class nuser extends javax.swing.JFrame {

    /**
     * Creates new form nuser
     */
    public nuser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        secque = new javax.swing.JTextField();
        secans = new javax.swing.JTextField();
        photo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jp2 = new javax.swing.JPasswordField();
        jp1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Upload Profile Pic");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 105, 183, 30));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 163, 183, 30));

        secque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secqueActionPerformed(evt);
            }
        });
        getContentPane().add(secque, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 326, 183, 30));

        secans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secansActionPerformed(evt);
            }
        });
        getContentPane().add(secans, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 380, 183, 30));
        getContentPane().add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 190, 230));

        jButton1.setText("Add User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 140, 40));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 40, 40));

        jp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp2ActionPerformed(evt);
            }
        });
        getContentPane().add(jp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 272, 180, 30));

        jp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp1ActionPerformed(evt);
            }
        });
        getContentPane().add(jp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/newuser.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        setSize(new java.awt.Dimension(689, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
String path="/Images/bookdef.png";
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        // Setting user's Picture folder as the current directory
        JFileChooser chooser = new JFileChooser(System.getProperty("user.home") + System.getProperty("file.separator")+ "Pictures");
        
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY); // We're not dealing with directories
        chooser.setAcceptAllFileFilterUsed(false); // Disabling 'All Files' Filter
        chooser.setDialogTitle("Choose a photo"); // Setting a custom title for our chooser
        chooser.setApproveButtonText("Upload"); // Replacing 'Open' with 'Upload'
              
        //chooser.setFileHidingEnabled(false);  // Show hidden files        
        //chooser.setMultiSelectionEnabled(true); // Allow multiple selections by pressing CTRL
        
        // Display all directories but only gif, jpg, jpeg or png files.
        chooser.setFileFilter(new FileFilter() {

            @Override
            public String getDescription() {
                return "All supported image formats";
            }

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".png")
                            || f.getName().toLowerCase().endsWith(".jpeg")
                            || f.getName().toLowerCase().endsWith(".jpg")
                            || f.getName().toLowerCase().endsWith(".gif");
                }
            }
        }); 
       
        // Show Dialog and store result in res
        int res = chooser.showOpenDialog(this);
        
        // Revert back to Metal L&F
      
        
        // If user clicked on Upload
        if (res == JFileChooser.APPROVE_OPTION) {            
            File file = chooser.getSelectedFile();
            // Creating ImageIcon out of the selected file
            
             path=file.getAbsolutePath();
            if(path.isEmpty())
                { path="/Images/bookdef.png";

                }
            
            
            ImageIcon image = new ImageIcon(path);
            // Get width and height of picLabel
            Rectangle rect = photo.getBounds();
            // Scaling the Image to fit in the picLabel
            Image scaledImage = image.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_DEFAULT);
            // Converting the image back to ImageIcon to make it acceptable by picLabel
            image = new ImageIcon(scaledImage);
            photo.setIcon(image);
            path=file.getAbsolutePath().replace('\\','/');
            
             
            
            
            
            
            
            
        } else {  // If the user clicked on cancel
            JOptionPane.showMessageDialog(this, "Dialog cancelled by the user");
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void secansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secansActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String ans=JOptionPane.showInputDialog(null,"Write Override Passcode.");
        
        
        if(ans.compareTo("Adminaccess")==0)
        {
            
        
        
        
        
        String nam="\""+name.getText()+"\"";
        String uname="\""+username.getText()+"\"";
        String secq="\""+secque.getText()+"\"";
        String seca="\""+secans.getText()+"\"";
        String pwd= new String (jp1.getPassword());
        String pwd1= new String (jp2.getPassword());

           
            
        String path1;


        path1="\""+path+"\"";
        
           
        if(pwd.compareTo(pwd1)==0)
        {        try{
            Class.forName("java.sql.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
            Statement s=conn.createStatement();
            String q= "insert into admina values("+nam+" ,"+uname+",\""+pwd+"\","+secq+","+seca+","+path1+")";
            int x=s.executeUpdate(q);

            if(x>0)
            {JOptionPane.showMessageDialog(null, "Account Succesfully Created");
            this.dispose();}
            else
            JOptionPane.showMessageDialog(null, "Account not Created");

        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }
        
        }else{
        
        JOptionPane.showMessageDialog(null, "Password do not Match");
        }}
        
        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jp2ActionPerformed

    private void secqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secqueActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jp1;
    private javax.swing.JPasswordField jp2;
    private javax.swing.JTextField name;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField secans;
    private javax.swing.JTextField secque;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
