
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.beans.Statement;
import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Devang Chhajed
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    public search() {
        initComponents();
        update();
         this.setIconImage(new ImageIcon(getClass().getResource("ico.png")).getImage());
        Toolkit toolkit = Toolkit.getDefaultToolkit();

Image img = toolkit.getImage("cur1.png");

Point point = new Point(0,0);
        Cursor cursor=toolkit.createCustomCursor(img, point, "Cursor"); 

   setCursor(cursor);
        
    }
    
    public void update(){
    DefaultTableModel rt=(DefaultTableModel)resulttable.getModel();
    try{
        Class.forName("java.sql.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
java.sql.Statement s=conn.createStatement();
String q= "select * from books order by Author";
ResultSet rs=s.executeQuery(q);
while(rs.next())
{String nam=rs.getString("Name");
 String aut=rs.getString("Author");
 String pub=rs.getString("Publisher");
 String gen=rs.getString("Genere");
 rt.addRow(new Object[]{nam,aut,pub,gen});
        
        }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        } 
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delete = new javax.swing.JFrame();
        FrameBar1 = new javax.swing.JLabel();
        delregno = new javax.swing.JTextField();
        delname = new javax.swing.JTextField();
        delgenre = new javax.swing.JTextField();
        delauthor = new javax.swing.JTextField();
        delphoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        publisher1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tablename = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resulttable = new javax.swing.JTable();
        tableauthor = new javax.swing.JLabel();
        tablepublisher = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FrameBar2 = new javax.swing.JLabel();
        tablegenere = new javax.swing.JLabel();
        tableback = new javax.swing.JLabel();
        editbutton = new javax.swing.JButton();
        uploadlab = new javax.swing.JLabel();
        editbutton1 = new javax.swing.JButton();
        publisher = new javax.swing.JTextField();
        genere = new javax.swing.JTextField();
        aname = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        dispback = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        searchback = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        delete.setMinimumSize(new java.awt.Dimension(690, 471));
        delete.setUndecorated(true);
        delete.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FrameBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        FrameBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameBar1MousePressed(evt);
            }
        });
        FrameBar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameBar1MouseDragged(evt);
            }
        });
        delete.getContentPane().add(FrameBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 40));

        delregno.setEditable(false);
        delete.getContentPane().add(delregno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 113, 180, 30));

        delname.setEditable(false);
        delete.getContentPane().add(delname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 169, 180, 30));

        delgenre.setEditable(false);
        delete.getContentPane().add(delgenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 225, 180, 30));

        delauthor.setEditable(false);
        delauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delauthorActionPerformed(evt);
            }
        });
        delete.getContentPane().add(delauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 279, 180, 30));
        delete.getContentPane().add(delphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 200, 240));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        delete.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 40, 40));

        publisher1.setEditable(false);
        delete.getContentPane().add(publisher1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 333, 180, 30));

        jButton1.setText("Delete Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        delete.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/deleteback.png"))); // NOI18N
        delete.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 470));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablename.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablenameMouseReleased(evt);
            }
        });
        getContentPane().add(tablename, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 140, 50));

        resulttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of the Book", "Author", "Publisher", "Genre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resulttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resulttableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(resulttable);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 560, 270));

        tableauthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableauthorMouseReleased(evt);
            }
        });
        getContentPane().add(tableauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 50));

        tablepublisher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablepublisherMouseReleased(evt);
            }
        });
        getContentPane().add(tablepublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 140, 50));

        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 60, 60));

        FrameBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        FrameBar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameBar2MousePressed(evt);
            }
        });
        FrameBar2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameBar2MouseDragged(evt);
            }
        });
        getContentPane().add(FrameBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 40));

        tablegenere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablegenereMouseReleased(evt);
            }
        });
        getContentPane().add(tablegenere, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 140, 50));

        tableback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/tableback1.png"))); // NOI18N
        getContentPane().add(tableback, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 790, 350));

        editbutton.setText("Edit");
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(editbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 380, 100, 30));
        getContentPane().add(uploadlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, 150, 150));

        editbutton1.setText("Delete");
        editbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(editbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 380, 100, 30));

        publisher.setEditable(false);
        publisher.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        publisher.setText("Publisher");
        publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherActionPerformed(evt);
            }
        });
        getContentPane().add(publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 320, 150, 30));

        genere.setEditable(false);
        genere.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        genere.setText("Genere");
        genere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genereActionPerformed(evt);
            }
        });
        getContentPane().add(genere, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 280, 150, 30));

        aname.setEditable(false);
        aname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aname.setText("Author");
        aname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anameActionPerformed(evt);
            }
        });
        getContentPane().add(aname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 240, 150, 30));

        bname.setEditable(false);
        bname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bname.setText("Name ");
        bname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnameActionPerformed(evt);
            }
        });
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 200, 150, 30));

        dispback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/viewdata.PNG"))); // NOI18N
        getContentPane().add(dispback, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 400, 250));

        search.setBackground(new java.awt.Color(153, 255, 153));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 170, 27));

        searchback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/search.PNG"))); // NOI18N
        getContentPane().add(searchback, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 230, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 510));

        setSize(new java.awt.Dimension(1279, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tablenameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablenameMouseReleased
click();
       
        tableback.setIcon(new ImageIcon("src/BackgroundImages/tableback1.png"));
        DefaultTableModel tm=(DefaultTableModel)resulttable.getModel();
        int i, count=tm.getRowCount();
        for(i=0;i<count;i++)
        { tm.removeRow(0);
        }

        try{
            Class.forName("java.sql.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
            java.sql.Statement s=conn.createStatement();
            String q= "select * from books order by Name";
            ResultSet rs=s.executeQuery(q);
            while(rs.next())
            {String nam=rs.getString("Name");
                String aut=rs.getString("Author");
                String pub=rs.getString("Publisher");
                String gen=rs.getString("Genere");
                tm.addRow(new Object[]{nam,aut,pub,gen});

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tablenameMouseReleased
int reg;

private void click(){
   try {
 // Open an audio input stream.
 URL url = this.getClass().getClassLoader().getResource("Sound/click.wav");
 AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
 // Get a sound clip resource.
 Clip clip = AudioSystem.getClip();
 // Open audio clip and load samples from the audio input stream.
 clip.open(audioIn);
 clip.start();
 } catch (Exception e1) {
 e1.printStackTrace();
 } 

}
    private void resulttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resulttableMouseClicked

        click();
        
       try{

            int row=resulttable.getSelectedRow();
            String tblclck=(resulttable.getModel().getValueAt(row, 0).toString());
            Class.forName("java.sql.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
            java.sql.Statement s=conn.createStatement();
            String q= "select * from books where Name =\""+ tblclck+"\"";
            ResultSet rs=s.executeQuery(q);
            while(rs.next())
            {bname.setText(rs.getString("Name"));
                aname.setText(rs.getString("Author"));
                genere.setText(rs.getString("Genere"));
                publisher.setText(rs.getString("Publisher"));
                reg=rs.getInt("RegNo");
                String path3=rs.getString("photo");

                if(path3.compareTo("null")==0)
                {    ImageIcon ii = new ImageIcon(getClass().getResource("/Images/bookdef.png"));

                    uploadlab.setIcon(ii);

                }else{

                    ImageIcon image = new ImageIcon(path3);
                    // Get width and height of picLabel
                    Rectangle rect = uploadlab.getBounds();
                    // Scaling the Image to fit in the picLabel
                    Image scaledImage = image.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_DEFAULT);
                    // Converting the image back to ImageIcon to make it acceptable by picLabel
                    image = new ImageIcon(scaledImage);
                    uploadlab.setIcon(image);

                }

            }

        }catch(Exception e){
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_resulttableMouseClicked

    private void tableauthorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableauthorMouseReleased
click();
               tableback.setIcon(new ImageIcon("src/BackgroundImages/tableback2.png"));

        DefaultTableModel tm=(DefaultTableModel)resulttable.getModel();

        int i, count=tm.getRowCount();
        for(i=0;i<count;i++)
        { tm.removeRow(0);
        }
        try{
            Class.forName("java.sql.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
            java.sql.Statement s=conn.createStatement();
            String q= "select * from books order by Author";
            ResultSet rs=s.executeQuery(q);
            while(rs.next())
            {String nam=rs.getString("Name");
                String aut=rs.getString("Author");
                String pub=rs.getString("Publisher");
                String gen=rs.getString("Genere");
                tm.addRow(new Object[]{nam,aut,pub,gen});

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tableauthorMouseReleased

    private void tablepublisherMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepublisherMouseReleased
click();
               tableback.setIcon(new ImageIcon("src/BackgroundImages/tableback3.png"));
        DefaultTableModel tm=(DefaultTableModel)resulttable.getModel();
        int i, count=tm.getRowCount();
        for(i=0;i<count;i++)
        { tm.removeRow(0);
        }

        try{
            Class.forName("java.sql.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
            java.sql.Statement s=conn.createStatement();
            String q= "select * from books order by Publisher";
            ResultSet rs=s.executeQuery(q);
            while(rs.next())
            {String nam=rs.getString("Name");
                String aut=rs.getString("Author");
                String pub=rs.getString("Publisher");
                String gen=rs.getString("Genere");
                tm.addRow(new Object[]{nam,aut,pub,gen});

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tablepublisherMouseReleased

    private void tablegenereMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablegenereMouseReleased
click();
               tableback.setIcon(new ImageIcon("src/BackgroundImages/tableback4.png"));
        DefaultTableModel tm=(DefaultTableModel)resulttable.getModel();
        int i, count=tm.getRowCount();
        for(i=0;i<count;i++)
        { tm.removeRow(0);
        }

        try{
            Class.forName("java.sql.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
            java.sql.Statement s=conn.createStatement();
            String q= "select * from books order by Genere";
            ResultSet rs=s.executeQuery(q);
            while(rs.next())
            {String nam=rs.getString("Name");
                String aut=rs.getString("Author");
                String pub=rs.getString("Publisher");
                String gen=rs.getString("Genere");
                tm.addRow(new Object[]{nam,aut,pub,gen});

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tablegenereMouseReleased

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
 
    deleteClass ob=new deleteClass();
        try{

            int row=resulttable.getSelectedRow();
            String tblclck=(resulttable.getModel().getValueAt(row, 0).toString());
            Class.forName("java.sql.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
            java.sql.Statement s=conn.createStatement();
            String q= "select * from books where Name =\""+ tblclck+"\"";
            ResultSet rs=s.executeQuery(q);
            while(rs.next())
            {ob.tbldel=rs.getInt("RegNo");
                update s1=new update();
                s1.setVisible(true);
            }

        }catch(Exception e){
           
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_editbuttonActionPerformed
String path;
    private void editbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbutton1ActionPerformed

    deleteClass ob=new deleteClass();
        try{

            int row=resulttable.getSelectedRow();
            String tblclck=(resulttable.getModel().getValueAt(row, 0).toString());
            Class.forName("java.sql.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
            java.sql.Statement s=conn.createStatement();
            String q= "select * from books where Name =\""+ tblclck+"\"";
            ResultSet rs=s.executeQuery(q);
            while(rs.next())
            {ob.tbldel=rs.getInt("RegNo");
                delete s1=new delete();
                s1.setVisible(true);
            }

        }catch(Exception e){
           
        }

        //delete.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_editbutton1ActionPerformed

    private void publisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherActionPerformed

    private void genereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genereActionPerformed

    private void anameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anameActionPerformed

    private void bnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnameActionPerformed

    private void FrameBar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameBar1MousePressed

    }//GEN-LAST:event_FrameBar1MousePressed

    private void FrameBar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameBar1MouseDragged

        // TODO add your handling code here:
    }//GEN-LAST:event_FrameBar1MouseDragged

    private void delauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delauthorActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        delete.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int regnum=Integer.parseInt(delregno.getText());
        int p = JOptionPane.showConfirmDialog(rootPane, "Do you want to delete this Record..","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0)
        {
            try{
                Class.forName("java.sql.Driver");
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
                java.sql.Statement s=conn.createStatement();
                String q= "delete from books where RegNo="+reg;

                int rs=s.executeUpdate(q);
                if (rs>0)
                JOptionPane.showMessageDialog(null, "Data Updated Successfully..");
                else
                JOptionPane.showMessageDialog(null, "Data Not Updated..");
            }
            catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_searchKeyPressed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        DefaultTableModel tm=(DefaultTableModel)resulttable.getModel();
        String searchf=search.getText();

        int i, count=tm.getRowCount();
        for(i=1;i<count;i++)
        { tm.removeRow(0);
        }

        try{
            Class.forName("java.sql.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/devangproject","root","");
            java.sql.Statement s=conn.createStatement();
            String q= "select * from books where Name like \""+searchf+"%\"";
            ResultSet rs=s.executeQuery(q);
            while(rs.next())
            {String nam=rs.getString("Name");
                String aut=rs.getString("Author");
                String pub=rs.getString("Publisher");
                String gen=rs.getString("Genere");
                tm.addRow(new Object[]{nam,aut,pub,gen});
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);}

        int count3=tm.getRowCount();
        tm.removeRow(count3);

        // TODO add your handling code here:
    }//GEN-LAST:event_searchKeyReleased

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked
int xMouse, yMouse;
    private void FrameBar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameBar2MousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_FrameBar2MousePressed

    private void FrameBar2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameBar2MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();

        this.setLocation(x-xMouse, y-yMouse);

        // TODO add your handling code here:
    }//GEN-LAST:event_FrameBar2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrameBar1;
    private javax.swing.JLabel FrameBar2;
    private javax.swing.JTextField aname;
    private javax.swing.JTextField bname;
    private javax.swing.JTextField delauthor;
    private javax.swing.JFrame delete;
    private javax.swing.JTextField delgenre;
    private javax.swing.JTextField delname;
    private javax.swing.JLabel delphoto;
    private javax.swing.JTextField delregno;
    private javax.swing.JLabel dispback;
    private javax.swing.JButton editbutton;
    private javax.swing.JButton editbutton1;
    private javax.swing.JTextField genere;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField publisher;
    private javax.swing.JTextField publisher1;
    private javax.swing.JTable resulttable;
    private javax.swing.JTextField search;
    private javax.swing.JLabel searchback;
    private javax.swing.JLabel tableauthor;
    private javax.swing.JLabel tableback;
    private javax.swing.JLabel tablegenere;
    private javax.swing.JLabel tablename;
    private javax.swing.JLabel tablepublisher;
    private javax.swing.JLabel uploadlab;
    // End of variables declaration//GEN-END:variables
}
